version: 2
jobs:
  screenshot_commit_and_push:
    docker:
      - image: circleci/node:10.16-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
      - run:
          command: npm install
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          command: |
            ./take-screenshot.js
            ./commit-and-push.sh

workflows:
  version: 2
  build:
    jobs:
      - screenshot_commit_and_push
  nightly:
    triggers:
      - schedule:
          cron: "40 12 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - screenshot_commit_and_push
